spring.application.name=tec-ms-batch-inyeccion-venta
server.port=8080
server.servlet.context-path=/batch-inyeccion-venta
spring.cloud.config.enabled=false

# Active Profile - Change this based on environment (dev, test, prod)
spring.profiles.active=dev

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Spring Batch Configuration
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always

# Scheduler Configuration
spring.task.scheduling.pool.size=5

# Logging
logging.level.ec.femsasalud.com.sales.injection.batch=INFO
#logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=DEBUG
#logging.level.reactor.netty.http.client.HttpClient=DEBUG
