spring.application.name=tec-ms-batch-inyeccion-venta
server.port=8080
server.servlet.context-path=/batch-inyeccion-venta
spring.cloud.config.enabled=false

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=DEBUG
#logging.level.reactor.netty.http.client.HttpClient=DEBUG
