# Production Environment Configuration

# SRI Configuration - PRODUCCIÓN
sri.wsdl.autorizacion.url=https://cel.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline?wsdl
sri.ambiente=2
sri.xml.storage.path=/factelectro/documentos2015/factelectro/documentos2015/factura/autorizado

# Database Configurations
spring.datasource.prod.jdbc-url=jdbc:oracle:thin:@(DESCRIPTION =(FAILOVER = ON)(LOAD_BALANCE = on)(ADDRESS = (PROTOCOL = TCP)(HOST = prsracscan)(PORT = 1521))(CONNECT_DATA =(SERVICE_NAME = PROD.UIO)))
spring.datasource.prod.username=weblink
spring.datasource.prod.password=weblink_2013
spring.datasource.prod.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.ginvoice.jdbc-url=jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 10.100.3.42)(PORT = 1521))(CONNECT_DATA =(SID = GPFDBQA)))
spring.datasource.ginvoice.username=ginvoice
spring.datasource.ginvoice.password=invoice2015
spring.datasource.ginvoice.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.adm.jdbc-url=jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 10.100.3.42)(PORT = 1521))(CONNECT_DATA =(SID = GPFDBQA)))
spring.datasource.adm.username=adm
spring.datasource.adm.password=adm2015
spring.datasource.adm.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.pgpostfy.jdbc-url=jdbc:oracle:thin:@(DESCRIPTION =(FAILOVER = ON)(LOAD_BALANCE = on)(ADDRESS = (PROTOCOL = TCP)(HOST = dbm0vm01-scan1)(PORT = 1521))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = PGPOSFY_SERV)))
spring.datasource.pgpostfy.username=gpf_lectura
spring.datasource.pgpostfy.password=Tur1ecf#fpg
spring.datasource.pgpostfy.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.stbi.jdbc-url=jdbc:oracle:thin:@(DESCRIPTION =(FAILOVER = ON)(LOAD_BALANCE = on)(ADDRESS = (PROTOCOL = TCP)(HOST = sgbiscan.gfybeca.int)(PORT = 1521))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = STBIPRD)))
spring.datasource.stbi.username=STAGE_COM
spring.datasource.stbi.password=Com21Stg20A
spring.datasource.stbi.driver-class-name=oracle.jdbc.OracleDriver

mongodb.host=10.100.15.119
mongodb.port=27017
mongodb.database=om-data-gpf
mongodb.username=dig_ti_user
mongodb.password=DIT.2025
mongodb.auth-database=admin
