# Test Environment Configuration

# SRI Configuration - PRUEBAS
sri.wsdl.autorizacion.url=https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline?wsdl
sri.ambiente=1
sri.xml.storage.path=/app/facturas/test

# Database Configurations
spring.datasource.prod.jdbc-url=jdbc:oracle:thin:@(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = 10.100.3.20)(PORT = 1521))(CONNECT_DATA =(SID = PRS6)))
spring.datasource.prod.username=weblink
spring.datasource.prod.password=weblink_2013
spring.datasource.prod.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.ginvoice.jdbc-url=jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 10.100.3.42)(PORT = 1521))(CONNECT_DATA =(SID = GPFDBQA)))
spring.datasource.ginvoice.username=ginvoice
spring.datasource.ginvoice.password=invoice2015
spring.datasource.ginvoice.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.adm.jdbc-url=jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 10.100.3.42)(PORT = 1521))(CONNECT_DATA =(SID = GPFDBQA)))
spring.datasource.adm.username=adm
spring.datasource.adm.password=adm2015
spring.datasource.adm.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.pgpostfy.jdbc-url=jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 10.100.3.70)(PORT = 1521))(CONNECT_DATA =(SERVER = DEDICATED) (SERVICE_NAME = QGPOSFY)))
spring.datasource.pgpostfy.username=GEOPOS
spring.datasource.pgpostfy.password=qgp0s_g3o
spring.datasource.pgpostfy.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.mom.jdbc-url=jdbc:oracle:thin:@(DESCRIPTION =(FAILOVER = ON)(LOAD_BALANCE = ON)(ADDRESS = (PROTOCOL = TCP)(HOST = vmcluts1scan.gfybeca.int)(PORT = 1521))(CONNECT_DATA = (SERVICE_NAME = momqa_pdb1.paas.oracle.com)) )
spring.datasource.mom.username=gpf_lectura
spring.datasource.mom.password=gpf_lectura1159
spring.datasource.mom.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.stbi.jdbc-url=jdbc:oracle:thin:@(DESCRIPTION =(FAILOVER = ON)(LOAD_BALANCE = on)(ADDRESS = (PROTOCOL = TCP)(HOST = sgbiscan.gfybeca.int)(PORT = 1521))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = STBIPRD)))
spring.datasource.stbi.username=STAGE_COM
spring.datasource.stbi.password=Com21Stg20A
spring.datasource.stbi.driver-class-name=oracle.jdbc.OracleDriver

mongodb.host=10.100.15.119
mongodb.port=27017
mongodb.database=om-data-gpf
mongodb.username=dig_ti_user
mongodb.password=DIT.2025
mongodb.auth-database=admin
