-- Spring Batch Tables for Oracle
-- Execute this script in your Oracle database in the schema where Spring Batch will run
-- Replace FARMACIAS with your desired schema if needed

-- Drop tables if they exist (optional - uncomment if you need to recreate)
-- DROP TABLE BATCH_STEP_EXECUTION_CONTEXT CASCADE CONSTRAINTS;
-- DROP TABLE BATCH_JOB_EXECUTION_CONTEXT CASCADE CONSTRAINTS;
-- DROP TABLE BATCH_STEP_EXECUTION CASCADE CONSTRAINTS;
-- DROP TABLE BATCH_JOB_EXECUTION_PARAMS CASCADE CONSTRAINTS;
-- DROP TABLE BATCH_JOB_EXECUTION CASCADE CONSTRAINTS;
-- DROP TABLE BATCH_JOB_INSTANCE CASCADE CONSTRAINTS;
-- DROP SEQUENCE BATCH_STEP_EXECUTION_SEQ;
-- DROP SEQUENCE BATCH_JOB_EXECUTION_SEQ;
-- DROP SEQUENCE BATCH_JOB_SEQ;

-- Create sequences
CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775806 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775806 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE BATCH_JOB_SEQ START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775806 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Create BATCH_JOB_INSTANCE table
CREATE TABLE BATCH_JOB_INSTANCE  (
    JOB_INSTANCE_ID NUMBER(19,0) NOT NULL PRIMARY KEY,
    VERSION NUMBER(19,0),
    JOB_NAME VARCHAR2(100) NOT NULL,
    JOB_KEY VARCHAR2(32) NOT NULL,
    CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
);

-- Create BATCH_JOB_EXECUTION table
CREATE TABLE BATCH_JOB_EXECUTION  (
    JOB_EXECUTION_ID NUMBER(19,0) NOT NULL PRIMARY KEY,
    VERSION NUMBER(19,0),
    JOB_INSTANCE_ID NUMBER(19,0) NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    START_TIME TIMESTAMP DEFAULT NULL,
    END_TIME TIMESTAMP DEFAULT NULL,
    STATUS VARCHAR2(10),
    EXIT_CODE VARCHAR2(2500),
    EXIT_MESSAGE VARCHAR2(2500),
    LAST_UPDATED TIMESTAMP,
    CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID)
    REFERENCES BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
);

-- Create BATCH_JOB_EXECUTION_PARAMS table
CREATE TABLE BATCH_JOB_EXECUTION_PARAMS  (
    JOB_EXECUTION_ID NUMBER(19,0) NOT NULL,
    PARAMETER_NAME VARCHAR2(100) NOT NULL,
    PARAMETER_TYPE VARCHAR2(100) NOT NULL,
    PARAMETER_VALUE VARCHAR2(2500),
    IDENTIFYING CHAR(1) NOT NULL,
    CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID)
    REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

-- Create BATCH_STEP_EXECUTION table
CREATE TABLE BATCH_STEP_EXECUTION  (
    STEP_EXECUTION_ID NUMBER(19,0) NOT NULL PRIMARY KEY,
    VERSION NUMBER(19,0) NOT NULL,
    STEP_NAME VARCHAR2(100) NOT NULL,
    JOB_EXECUTION_ID NUMBER(19,0) NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    START_TIME TIMESTAMP DEFAULT NULL,
    END_TIME TIMESTAMP DEFAULT NULL,
    STATUS VARCHAR2(10),
    COMMIT_COUNT NUMBER(19,0),
    READ_COUNT NUMBER(19,0),
    FILTER_COUNT NUMBER(19,0),
    WRITE_COUNT NUMBER(19,0),
    READ_SKIP_COUNT NUMBER(19,0),
    WRITE_SKIP_COUNT NUMBER(19,0),
    PROCESS_SKIP_COUNT NUMBER(19,0),
    ROLLBACK_COUNT NUMBER(19,0),
    EXIT_CODE VARCHAR2(2500),
    EXIT_MESSAGE VARCHAR2(2500),
    LAST_UPDATED TIMESTAMP,
    CONSTRAINT JOB_EXEC_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID)
    REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

-- Create BATCH_STEP_EXECUTION_CONTEXT table
CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT  (
    STEP_EXECUTION_ID NUMBER(19,0) NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR2(2500) NOT NULL,
    SERIALIZED_CONTEXT CLOB,
    CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID)
    REFERENCES BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
);

-- Create BATCH_JOB_EXECUTION_CONTEXT table
CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT  (
    JOB_EXECUTION_ID NUMBER(19,0) NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR2(2500) NOT NULL,
    SERIALIZED_CONTEXT CLOB,
    CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID)
    REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

-- Create indexes for better performance
CREATE INDEX JOB_INST_UN_IDX ON BATCH_JOB_INSTANCE (JOB_NAME, JOB_KEY);
CREATE INDEX JOB_EXEC_INST_ID_IDX ON BATCH_JOB_EXECUTION (JOB_INSTANCE_ID);
CREATE INDEX STEP_EXEC_JOB_EXEC_ID_IDX ON BATCH_STEP_EXECUTION (JOB_EXECUTION_ID);
